# Generated by Django 4.1 on 2022-09-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={},
        ),
    ]
